lesoryb/mainapp/urls.py
from django.urls import re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

import mainapp.views as views

app_name = 'mainapp'

urlpatterns = [
    re_path('^$', views.index, name='index'),
    re_path('^rules', views.rules, name='rules'),
    re_path('^contact', views.contact, name='contact'),
    re_path('^privacy', views.privacy, name='privacy'),
    re_path('^games', views.games, name='games'),
    re_path('^cookies', views.cookies, name='cookies'),
    re_path('^news/$', views.newslist, name='newslist'),
    re_path('^callme', views.callme, name='callme'),
    re_path('^book', views.book, name='book'),
    re_path('^birthday', views.birthday, name='birthday'),
    re_path('^giftcards', views.giftcards, name='giftcards'),
    re_path('^news/(?P<pk>\d+)/', views.news, name='newslist'),
    re_path('^sitemap.xml', views.sitemap, name='sitemap'),
    re_path('^robots.txt$', TemplateView.as_view(
        template_name='mainapp/robots.txt')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

lesoryb/mainapp/models.py
from django.db import models

# Create your models here.


class Arena(models.Model):
    name = models.CharField(max_length=10, blank=False)
    rusname = models.CharField(max_length=10, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        managed = True
        db_table = 'arena'


class InstagramPost(models.Model):
    code = models.CharField(max_length=50, blank=False)
    created = models.DateField(blank=True, null=True)


    def __str__(self):
        return self.code

    class Meta:
        managed = True
        db_table = 'instagrampost'


class NewsArticle(models.Model):
    title = models.TextField(max_length=5000, blank=False)
    img = models.ImageField(blank=True)
    tags = models.ManyToManyField(to='NewsTag', blank=True)
    text = models.TextField(max_length=5000, blank=False)
    postdate = models.DateField()
    htmlcode = models.TextField(max_length=50000, blank=True)


    def __str__(self):
        return self.title

    class Meta:
        managed = True
        db_table = 'newsarticle'


class NewsTag(models.Model):
    tag = models.CharField(max_length=20, blank=False)
    posts = models.ManyToManyField(to='NewsArticle', blank=True)

    def __str__(self):
        return self.tag

    class Meta:
        managed = True
        db_table = 'newstag'

lesoryb/mainapp/views.py
from authapp.forms import LesorubUserLoginForm
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail

from .models import NewsArticle, InstagramPost


def index(request):
    login_form = LesorubUserLoginForm(data=request.POST or None)
    lastnewslist = NewsArticle.objects.all().order_by('-postdate')[:3]
    posts = InstagramPost.objects.all().order_by('-created')[:4]
    description = "LONG MULTILINE TEXT"
    context = {'title': 'Лесоруб ',
               'login_form': login_form,
               'description': description,
               'newslist': lastnewslist,
               'posts': posts,
               }
    return render(request, 'mainapp/xxx.html', context)


def rules(request):
    description = 'LONG MULTILINE TEXT'
    context = {'title': 'Лесоруб',
               'description': description,
               }
    return render(request, 'mainapp/xxx.html', context)


def contact(request):
    description = 'LONG MULTILINE TEXT'
    context = {'title': 'Лесоруб',
               'description': description,
               }
    return render(request, 'mainapp/xxx.html', context)


def privacy(request):
    description = 'LONG MULTILINE TEXT'
    context = {'title': 'Лесоруб',
               'description': description,
               }
    return render(request, 'mainapp/xxx.html', context)


def newslist(request):
    articles = NewsArticle.objects.all().order_by('-postdate')
    description = 'LONG MULTILINE TEXT'
    context = {'title': 'Лесоруб',
               'description': description,
               'articles': articles,
               }
    return render(request, 'mainapp/xxx.html', context)


def news(request, pk):
    article = NewsArticle.objects.get(pk=pk)
    latestnews = NewsArticle.objects.all().order_by('-postdate')[:3]
    description = 'LONG MULTILINE TEXT'
    context = {'title': 'Лесоруб',
               'latestnews': latestnews,
               'description': description,
               'article': article,
               'text': article.text.split('\n'),
               }
    return render(request, 'mainapp/news.html', context)


def cookies(request):
    description = 'LONG MULTILINE TEXT'
    context = {'title': 'Лесоруб',
               'description': description,
               }
    return render(request, 'mainapp/xxx.html', context)


def callme(request):
    try:
        phone = request.POST['myphone']
        path = request.POST['path']
        send_mail('Запрос на звонок', str(phone) + '\n' + str(path),
                  'mail@mail.com', ['mail@mail.com'])
        response = HttpResponse(status=200, content='success')
    except Exception:
        response = HttpResponse(status=400, content='failed')
    return response


def book(request):
    try:
        phone = request.POST['phone']
        path = request.POST['path']
        date = request.POST['date']
        time = request.POST['time']
        comments = request.POST['comments']
        message = ' '.join(('Запрос брони\n',
                            str(phone),
                            '\n',
                            str(time),
                            str(date),
                            '\n',
                            str(comments),
                            '\n\n', str(path)))
        send_mail('Запрос на звонок',
                  message,
                  'lesorubmoscow@gmail.com',
                  ['lesorubmoscow@gmail.com'])
        response = HttpResponse(status=200, content='success')
    except Exception:
        response = HttpResponse(status=400, content='failed')
    return response


def birthday(request):
    description = 'LONG MULTILINE TEXT'
    context = {'title': 'LONG MULTILINE TEXT',
               'description': description}
    return render(request, 'mainapp/xxx.html', context)


def birthday2(request):
    description = 'LONG MULTILINE TEXT'
    context = {'title': 'LONG MULTILINE TEXT',
               'description': description}
    return render(request, 'mainapp/xxx.html', context)


def games(request):
    description = 'LONG MULTILINE TEXT'
    context = {'title': 'Лесоруб',
               'description': description,
               }
    return render(request, 'mainapp/xxx.html', context)


def giftcards(request):
    description = 'LONG MULTILINE TEXT'
    context = {'title': 'Лесоруб',
               'description': description,
               }
    return render(request, 'mainapp/xxx.html', context)


def sitemap(request):
    context = {}
    return render(request, 'mainapp/sitemap.xml', context)

lesoryb/mainapp/templates/mainapp/banner.html
{% load i18n %}

<div id="CookielawBanner">
    <div class="container">
        <h6>Соглашение об использовании cookie-файлов</h6>
        <p>
            <a class="btn btn-primary pull-right" href="javascript:Cookielaw.createCookielawCookie();">Принимаю</a>
            <!--{% trans "COOKIE_INFO_PARA" %}-->
            Наш сайт сохранит анонимные идентификаторы (cookie-файлы) на ваше устройство. Это способствует персонализации контента, а также используется в статистических целях. Вы можете отключить использование cookie-файлов, изменив настройки Вашего браузера. Пользуясь этим сайтом при настройках браузера по умолчанию, вы соглашаетесь на использование cookie-файлов и сохранение информации на Вашем устройстве.
        </p>
    </div>
</div>

lesoryb/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <title>{{title}}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="google-site-verification" content="BQN8SmFtByZd3gCb6la4kT4FFlhTrwevBxLAZR-PZxQ" />
    <meta name="keywords" content="метание топора, метать топоры в Москве, кидать топор, axe throwing in Moscow, throw axe in Moscow, небоулинг, недартс, дартс">
    <meta name="description" content="{{description}}">
    <meta name="yandex-verification" content="a2008290296ce436" />
    <link rel="icon" href="{% static 'images/favicon.png' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<!--    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}"> -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">



    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/mytemplatecss.css' %}">
    <!-- Yandex.Metrika counter --> <script type="text/javascript" > (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)}; m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)}) (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym"); ym(52873213, "init", { clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); </script> <noscript><div><img src="https://mc.yandex.ru/watch/52873213" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->

    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-136512379-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-136512379-1');
</script>

    <!-- Facebook Pixel Code -->
  <script>
    !function(f,b,e,v,n,t,s)
    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
    n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t,s)}(window, document,'script',
    'https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '300961727451750');
    fbq('track', 'PageView');
  </script>
  <noscript><img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=300961727451750&ev=PageView&noscript=1"
  /></noscript>
<!-- End Facebook Pixel Code -->

  </head>
  <body>

	<!-- navbar -->
	{% include 'mainapp/includes/navbar.html' %}

    {%block body%}



    {%endblock%}
    <div style="position:fixed; top:auto; bottom:0; background:black; width:100%">
      {% load cookielaw_tags %}
      {% cookielaw_banner %}
    </div>
    <script>
    jQuery(document).ready(function() {
      var btn = $('#scrolltotop');
      $(window).scroll(function() {
        if ($(window).scrollTop() > 100) {
          btn.addClass('show');
        } else {
          btn.removeClass('show');
        }
      });
      btn.on('click', function(e) {
        e.preventDefault();
        $('html, body').animate({scrollTop:0}, '100');
      });
    });
    </script>
    <a id="scrolltotop"></a>

  </body>
</html>

lesoryb/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block body %}

<section class="ftco-section contact-section">
      <div class="container mt-5">
        <div class="row block-9">
					<div class="col-md-4 contact-info ftco-animate fadeInUp ftco-animated">
						<div class="row">
							<div class="col-md-12 mb-4">
	              <h2 class="h4">Контактная информация</h2>
	            </div>
	            <div class="col-md-12 mb-3">
	              <p><span>Адрес:</span> г. Москва, Звенигородское шоссе, 4</p>
                    <p>ТЦ Электроника на Пресне, павильоны Д2-Д8, зеленая линия.</p>
					<p>1. Центральный вход со стороны Звенигородского шоссе, проходите по синей линии до поворота на зеленую линию.</p>
					<p>2. На повороте на зеленую линию вы увидите наши стеклянные двери.</p>

	            </div>
	            <div class="col-md-12 mb-3">
	              <p><span>Телефон:</span> <a href="tel:+74994507707">+ 7 499 450 7707</a></p>
	            </div>
	            <div class="col-md-12 mb-3">
	              <p><span>Email:</span> <a href="mailto:lesorubmoscow@gmail.com">lesorubmoscow@gmail.com</a></p>
	            </div>
						</div>
					</div>
					<div class="col-md-1"></div>
          <div class="col-md-6 ftco-animate fadeInUp ftco-animated">
            <h5>Оставьте заявку на игру</h5>
					<form bookform
						  onsubmit="ym(52873213, 'reachGoal', 'RESERVE'); return true;"
						  action="book/"
						  class="appointment-form">
					{%csrf_token%}
					<div class="form-group ">
						<input type="tel" class="form-control" maxlength="15"
							   placeholder="Ваш телефон"
							   required
							   name="phone">
					</div>
	    				<div class="d-md-flex">
		    				<div class="form-group">
		    					<div class="input-wrap">
		            				<div class="icon"><span class="ion-md-calendar"></span></div>
		            				<input type="text" name="date" class="form-control appointment_date" placeholder="Дата">
	            				</div>
		    				</div>
		    				<div class="form-group ml-md-4">
		    					<div class="input-wrap">
									<div class="icon"><span class="ion-ios-clock"></span></div>
									<input type="text" name="time" class="form-control appointment_time" placeholder="Время">
								</div>
							</div>
	    				</div>
	    				<div class="d-md-flex">
	    					<div class="form-group">
		              			<textarea name="comments" id="" cols="30" rows="2" class="form-control" placeholder="Примечания"></textarea>
		            		</div>
							<div class="form-group ml-md-4">
							  <input type="submit" value="Отправить заявку" class="btn btn-primary py-3 px-4" data-toggle="tooltip" title="Бронирование онлайн временно не работает. Пишите нам на почту или звоните.">
							</div>
						</div>
				</form>
			  		{% if 1 == 0 %}
			  			<form callme1 action="callme">
						<div class="form-group ml-md-4">
							<input type="tel" class="form-control" maxlength="15"
								   placeholder="Ваш телефон"

								   required
									name="myphone1">
							{%csrf_token%}
						</div>
						<div class="form-group ml-md-4">
						  <input type="submit" value="Перезвоните мне"  class="btn btn-primary py-3 px-4" data-toggle="tooltip">
						</div>
						</form>
			  		{%endif%}
			  <!--
			  <form action="#" class="contact-form" aria-disabled="true">
            	<div class="row">
            		<div class="col-md-6">
	                <div class="form-group">
	                  <input type="text" class="form-control" placeholder="Имя">
	                </div>
                </div>
                <div class="col-md-6">
	                <div class="form-group">
	                  <input type="text" class="form-control" placeholder="Email">
	                </div>
	                </div>
              </div>
              <div class="form-group">
                <textarea name="" id="" cols="30" rows="7" class="form-control" placeholder="Сообщение"></textarea>
              </div>
                <div class="form-group">
                    <input type="checkbox" name="agreement"> Я прочитал <a href="{% url 'mainapp:privacy'%}">политику обработки персональных данных</a> и даю согласие на их обработку.
                </div>
              <div class="form-group">
                <input type="submit" disabled data-toggle="tooltip" title="отправка сообщений временно не работает. Пишите нам на почту" value="Отправить" class="btn btn-primary py-3 px-5">
              </div>
            </form>
            -->
          </div>
        </div>
      </div>
    </section>
<section class="ftco-gallery">
	<div class="container-wrap">
		<div class="row no-gutters">
			<div class="col-md-3 ftco-animate fadeInUp ftco-animated">
				<a class='gallery img d-flex align-items-center'
				   style="background-image: url('{%static 'images/route1.jpg'%}')"></a>
			</div>
			<div class="col-md-3 ftco-animate fadeInUp ftco-animated">
				<a class='gallery img d-flex align-items-center'
				   style="background-image: url('{%static 'images/route4.jpg'%}')"></a>
			</div>
			<div class="col-md-3 ftco-animate fadeInUp ftco-animated">
				<a class='gallery img d-flex align-items-center'
				   style="background-image: url('{%static 'images/route3.jpg'%}')"></a>
			</div>
			<div class="col-md-3 ftco-animate fadeInUp ftco-animated">
				<a class='gallery img d-flex align-items-center'
				   style="background-image: url('{%static 'images/route5.jpg'%}')"></a>
			</div>
		</div>
	</div>
</section>
<div ftco-section ftco-no-pb>
    <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3Adfa5da600774540d748688e9a6347d72a470e19523197343d2c00cd720ec36bf&amp;source=constructor" width="100%" height="500em" frameborder="0"></iframe>
</div>
{% include 'mainapp/includes/footer.html' %}
{% include 'mainapp/includes/js.html' %}
{%endblock%}

lesoryb/mainapp/templates/mainapp/includes/navbar.html
{% load static %}
{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="/">
			<img class="logo" src="{% static 'images/logowhite.png'%}">
          </a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>
	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item
	          {%if request.path == '/' %}active{%endif%}
                "><a href="/" class="nav-link">Главная</a></li>
	          <li class="nav-item {%if request.path == '/rules/' %}active{%endif%}"><a href="{% url 'mainapp:rules' %}" class="nav-link">Наши правила</a></li>
	          <li class="nav-item"><a href="/#prices" class="nav-link">Цены</a></li>
	          <li class="nav-item {%if request.path == '/giftcards/' %}active{%endif%}"><a href="{% url 'mainapp:giftcards' %}" class="nav-link">Подарочные карты</a></li>
	          <li class="nav-item {%if request.path == '/games/' %}active{%endif%}"><a href="{% url 'mainapp:games' %}" class="nav-link">Игры</a></li>
	          <li class="nav-item {%if request.path == '/news/' %}active{%endif%}"><a href="{% url 'mainapp:newslist' %}" class="nav-link">Новости</a></li>

				<li class="nav-item {%if request.path == '/contact/' %}active{%endif%}"><a href="{% url 'mainapp:contact' %}" class="nav-link">Контакты</a></li>

	        </ul>
          </div>
        </div>
    </nav>
{% endblock %}

lesoryb/mainapp/templates/mainapp/index_components/home_gallery.html
{% load static %}
<section class="ftco-gallery">
    	<div class="container-wrap">
    		<div class="row no-gutters">
					{%for post in posts%}
					<div class="col-md-3 ftco-animate">
						<a href="https://instagram.com/p/{{post.code}}/" class="gallery img d-flex align-items-center"
						   style="background-image: url(https://instagram.com/p/{{post.code}}/media/?size=m)">
							<div class="icon mb-4 d-flex align-items-center justify-content-center">
    						<span class="icon-search"></span>
    					</div>
						</a>
					</div>
					{%endfor%}

        </div>
    	</div>
    </section>

lesoryb/mainapp/templates/mainapp/index_components/home_rules.html
{% load static %}
<section class="ftco-section ftco-bg-dark">
    <div class="container">
        <div class="row justify-content-center mb-5">
          <div class="col-md-7 heading-section text-center ftco-animate fadeInUp ftco-animated">
        <h2 class="mb-4">Что такое - метание топоров?</h2>
        <p>Вероятно Вы никогда не слышали о метании топоров. Мы не только расскажем Вам об этом, но и объясним как это делать и дадим попробовать.</p>
        <p>Первый вопрос, который прийдет Вам в голову скорее всего будет: "Разве это безопасно?" И наш ответ: "Конечно же да!"
            При соблюдении нескольких простых правил метание топоров не только безопасный, но и безумно веселый способ провести время!
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 ftco-animate fadeInUp ftco-animated">
        <div class="media d-block text-center block-6 services">
          <div class="icon d-flex justify-content-center align-items-center mb-5">
            <span class="flaticon1-teacher"></span>
          </div>
          <div class="media-body">
            <h3 class="heading">Пройти инструктаж</h3>
            <p>Перед каждой игровой сессией инструктор расскажет Вам как безопасно вести себя во время метания топоров,
              о правилах топор-клуба и покажет как метать топоры.
            </p>
          </div>
        </div>
      </div>
      <div class="col-md-4 ftco-animate fadeInUp ftco-animated">
        <div class="media d-block text-center block-6 services">
          <div class="icon d-flex justify-content-center align-items-center mb-5">
            <span class="flaticon1-safety"></span>
          </div>
          <div class="media-body">
            <h3 class="heading">Следовать правилам безопасности</h3>
            <p>Мы разработали ряд правил соблюдение которых, обеспечит безопасность и комфорт для Вас и других посетителей топор-клуба "Лесоруб".
            <a href="{% url 'mainapp:rules' %}">Читать правила</a></p>
          </div>
        </div>
      </div>

      <div class="col-md-4 ftco-animate fadeInUp ftco-animated">
        <div class="media d-block text-center block-6 services">
          <div class="icon d-flex justify-content-center align-items-center mb-5">
            <span class="flaticon1-axe"></span></div>
          <div class="media-body">
            <h3 class="heading">Веселиться</h3>
            <p>Топор-клуб "Лесоруб" - в первую очередь развлекательное заведение.
                И хотя метание топоров приобретает все большую популярность в мире как вид спорта,
                мы видим это как способ повеселиться и отдохнуть.
            </p>
          </div>
        </div>
      </div>
    </div>
    </div>
</section>

lesoryb/mainapp/templates/mainapp/index_components/home_shortrules.html
{%load static%}

<section class="ftco-section">
    	<div class="container">
    		<div class="row align-items-center">
    			<div class="col-md-6 pr-md-5">
    				<div class="heading-section text-md-right ftco-animate fadeInUp ftco-animated">
	          	<span class="subheading"></span>
	            <h2 class="mb-4">Краткие правила поведения</h2>
	            <p class="mb-4">Мы разработали ряд простых правил, чтобы все посетители чувствовали себя комфортно и безопасно в нашем клубе.
                    Перед входом в игровую зону мы просим всех игроков без исключения подписать согласие с правилами поведения в клубе.
                    Обращаем Ваше внимание, что при не соблюдении правил клуба персонал имеет право отказать в допуске к играм или попросить покинуть клуб.
                    Вот краткая выжимка из них.
                </p>
	            <p><a href="{% url 'mainapp:rules' %}" class="btn btn-primary btn-outline-primary px-4 py-3">Полные правила топор-клуба "Лесоруб"</a></p>
	          </div>
    			</div>
    			<div class="col-md-6">
    				<div class="program d-flex ftco-animate fadeInUp ftco-animated">
							<div class="icon d-flex justify-content-center align-items-center">
								<span class="flaticon4-pluseighteen"></span>
							</div>
							<div class="text ml-5">
								<h3>Берите с собой паспорт</h3>
								<p>Перед оплатой и входом в игоровую зону мы попросим Вас подписать ознакомиться с правилами клуба,
									техникой безопасности и подписать форму ознакомления с ними. Для этого Вам понадобится паспорт. Не забудьте его!
                                </p>
							</div>
  					</div>

					<div class="program d-flex ftco-animate fadeInUp ftco-animated">
							<div class="icon d-flex justify-content-center align-items-center">
								<span class="flaticon2-booze"></span>
							</div>
							<div class="text ml-5">
								<h3>Приходить в клуб можно только трезвым</h3>
								<p>Мы допускаем в наш топор-клуб только трезвых посетителей. Если Вы уже приняли на грудь,
                                    наш сотрудник будет иметь право отказать Вам в допуске к метанию топоров и духовой трубке.
                                    Со временем мы можем пересмотреть нашу политику в отношении слабого алкоголя в игровой зоне.
                                </p>
							</div>
  					</div>
  					<div class="program d-flex ftco-animate fadeInUp ftco-animated">
							<div class="icon d-flex justify-content-center align-items-center">
								<span class="flaticon2-boots"></span>
							</div>
							<div class="text ml-5">
								<h3>Допускается носить только закрытую обувь</h3>
								<p>По соображениям безопасности мы настоятельно рекомендуем Вам приходить к нам в закрытой обуви.
                                Мы приветствуем ботинки, сапоги, ботфорты, ботильоны и т.д., но не разрешим Вам метать топоры в шлепках, сандалиях или тапочках.
                                </p>
							</div>
  					</div>
  					<div class="program d-flex ftco-animate fadeInUp ftco-animated">
							<div class="icon d-flex justify-content-center align-items-center">
								<span class="flaticon1-axe"></span>
							</div>
							<div class="text ml-5">
								<h3>Свои топоры запрещены</h3>
								<p>Поскольку топор является предметом бытовым, мы допускаем, что у Вас может быть с собой парочка
                                в Вашей дамской сумочке или дипломате. Однако мы не разрешаем находиться в игровой зоне посетителям со своими топорами, пилами, дрелями и т.д.
                                    Равно как и вход с холодным или огнестрельным оружием в топор-клуб также запрещен.
                                </p>
							</div>
  					</div>
  					<div class="program d-flex ftco-animate fadeInUp ftco-animated">
							<div class="icon d-flex justify-content-center align-items-center">
								<span class="flaticon2-delivery"></span>
							</div>
							<div class="text ml-5">
								<h3>BYOF -  приносите свою еду</h3>
								<p>Метание топоров не только весело, но и утомительно. Но у нас нет своей кухни, чтобы Вас накормить.
                                Поэтому мы приветствуем, если Вы принесете свою еду или закажете доставку прямо к нам.
                                    Единственная просьба при этом: соблюдать чистоту и порядок и убирать за собой.
                                    Пока мы можем предложить Вам только безалкогольные напитки и воду.

                                </p>
							</div>
  					</div>
  					<div class="program d-flex ftco-animate fadeInUp ftco-animated">
							<div class="icon d-flex justify-content-center align-items-center">
								<span class="flaticon2-polite"></span>
							</div>
							<div class="text ml-5">
								<h3>Будьте вежливы и слушайтесь инструктора</h3>
								<p>Метание топров, дартс или распил бревна - это соревновательные развлечения. Вокруг Вас будут
                                такие же люди, которые хотят весело провести время. И потому важнейшим правилом нашего клуба является
                                вежливость по отношению к другим игрокам и посетителям клуба.
                                </p>
							</div>
  					</div>
    			</div>
    		</div>
    	</div>
    </section>